### ISSUE TITLE
Readonly Properties in Target cause error

### ISSUE THREAD

**Issue by droyad** [kkozmic/Cartographer#13]
Fix in MatchByNameMappingPattern

```
foreach (var targetProperty in strategy.Target.GetProperties()
.Where(p => p.CanWrite)
)
```

**Comment by kkozmic** [comment]
Thanks for that.

It's a bit more complicated though. `p.CanWrite` will tell you if the property has setter, but it won't tell you if that setter is accessible. We'll need to consider usage of `InternalsVisibleToAttribute` for access to internal properties...

I think we're at a point where we need to start building richer model around those things.

**Comment by kkozmic** [comment]
temporarily fixed. More in-depth fix will be required as part of larget re-organization of internal structure of mapping model, which will happen at some later point :)
