### ISSUE TITLE
.Convert(object a, object b) does not work if b is an interface

### ISSUE THREAD

**Issue by droyad** [kkozmic/Cartographer#8]
```
MyType a = new MyType();
IMyOtherType a = new MyOtherType();
mapper.Convert(a, b)
```

Results in:
Target type must have single public constructor. This is the only scenario supported at the moment.

**Comment by kkozmic** [comment]
Is this latest version from the source or alpha 1?
You might need a ITypeMatcher for now to work around it, that will take
actual type as the target of the mapping.

But I guess when mapping into existing object looking for constructors is
not needed at all.
On Jun 5, 2012 8:47 AM, "Robert Wagner" <
reply@reply.github.com>
wrote:

**Comment by droyad** [comment]
Alpha (from NuGet). Worked around it by casting to the relevant type.

On 5 June 2012 16:57, Krzysztof Koźmic <
reply@reply.github.com

**Comment by kkozmic** [comment]
Ok

I'll get it fixed this week hopefully for alpha 2
On Jun 5, 2012 9:07 AM, "Robert Wagner" <
reply@reply.github.com>
wrote:

**Comment by kkozmic** [comment]
That's actually already fixed in current master
